title: napari-n2v
description: "A self-supervised denoising algorithm.<br>
<ul>
  <li><a href=\"index.html\">Home</a></li>
  <li><a href=\"installation.html\">Installation</a></li>
  <li><a href=\"documentation.html\">Documentation</a></li>
  <li><a href=\"examples.html\">Examples</a></li>
  <li><a href=\"faq.html\">Troubleshooting</a></li>  
</ul>"
logo: images/juglab_logo_128.png
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme